(() => {
 'use strict';
 const modal=document.getElementById('trip-funding-modal'),body=document.getElementById('trip-funding-body');if(!modal)return;
 const esc=value=>App.escapeHtml(value??'');const money=value=>value===null||value===undefined?'Not Available':(window.fleetCurrencySymbol||'₱')+Number(value).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
 let current=null,serial=0,timer=null,sending=false;
 async function load(params){const response=await fetch(`${window.TC_BASE_URL}/actions/trip-funding.php?${params}`,{cache:'no-store',credentials:'same-origin'});const data=await response.json();if(!data.ok)throw Error(data.error);return data.data;}
 function render(data){
  current=data;const e=data.estimate,f=data.request,pending=data.status==='Pending Finance Approval',confirmed=data.status==='Funding Confirmed',pretrip=['Assigned','Confirmed','Scheduled'].includes(data.trip.status);
  const editable=data.can_manage && pretrip && !pending && !confirmed && !(e.issues||[]).length;
  const info=pairs=>`<dl class="funding-info">${pairs.map(([label,value])=>`<dt>${esc(label)}</dt><dd>${esc(value)}</dd>`).join('')}</dl>`;
  body.innerHTML=`<div class="funding-grid"><section class="funding-section"><h3>Trip & Assignment</h3>${info([['Trip',data.trip.id],['Reservation',data.trip.reservation_id],['Driver',data.trip.driver||'Not assigned'],['Vehicle',data.trip.vehicle],['Route',data.trip.origin+' → '+data.trip.destination]])}</section><section class="funding-section"><h3>Estimated Trip Cost</h3>${info([['Distance',e.distance_km?Number(e.distance_km).toFixed(2)+' km':'Not Available'],['Expected Efficiency',e.expected_km_per_liter?e.expected_km_per_liter+' km/L'+(e.efficiency_source==='Type estimate'?' (type estimate)':''):'Not Available'],['Estimated Fuel',e.estimated_liters?Number(e.estimated_liters).toFixed(2)+' L':'Not Available'],['Reference Price',money(e.reference_price)+' / L'],['Estimated Fuel Cost',money(e.estimated_fuel_cost)],['Toll / Parking','Not Included in Estimate'],['Estimated Trip Cost',money(e.estimated_total_cost)]])}</section></div>
   ${(e.issues||[]).length?`<p class="funding-warning">${e.issues.map(esc).join('<br>')}</p>`:''}
   <div class="funding-status ${confirmed?'confirmed':''}" role="status">${pending?'<span class="spinner-border spinner-border-sm" aria-hidden="true"></span>':''}<strong>${esc(data.status)}</strong>${pending?'<span>Waiting for Finance approval… (5 seconds)</span>':''}</div>
   ${editable?`<form id="funding-request-form"><div class="funding-controls"><div><label class="tc-form-label" for="funding-method">Funding Method</label><select id="funding-method" name="funding_method" class="tc-form-select" required>${data.methods.map(m=>`<option value="${esc(m.code)}">${esc(m.name)}</option>`).join('')}</select></div><div><label class="tc-form-label" for="funding-amount">Requested Funding Amount / Limit</label><input id="funding-amount" name="requested_amount" class="tc-form-control" type="number" step="0.01" min="${Number(e.estimated_total_cost).toFixed(2)}" value="${Number(e.estimated_total_cost).toFixed(2)}" required></div></div><div class="funding-toolbar"><button class="tc-btn tc-btn-primary" type="submit"><i class="bi bi-send" aria-hidden="true"></i> Send Request to Finance</button></div></form>`:f?`<section class="funding-section">${info([['Funding Request','#'+f.id],['Funding Method',f.method_name],['Requested Funding',money(f.requested_amount)],['Approved Funding',f.approved_amount?money(f.approved_amount):'Not approved'],['Source','Mock Finance — Test Mode'],['Approval Status',f.approval_status||'Pending'],['Approved At',f.approved_at?new Date(f.approved_at.replace(' ','T')).toLocaleString():'Not approved']])}</section>`:''}
   <p class="funding-note">${confirmed?'The estimate and reference fuel price are saved snapshots. ':''}Approved funding is a spending limit, not an actual expense.</p>
   ${pretrip?`<section class="funding-section"><h3>Dispatch Requirements</h3><ul class="funding-checks">${Object.entries(data.readiness.checks).map(([label,ok])=>`<li><i class="bi ${ok?'bi-check-circle-fill text-success':'bi-dash-circle text-muted-custom'}" aria-hidden="true"></i>${esc(label)}</li>`).join('')}</ul><p class="funding-note">${data.readiness.ready?'Ready for Dispatch':pending?'Waiting for Finance Approval':'Complete all requirements before dispatch.'}</p>${data.readiness.reasons.length?`<p class="funding-note">${data.readiness.reasons.map(esc).join(' · ')}</p>`:''}</section>`:''}
   <div class="funding-error" id="funding-error" role="alert"></div>
   ${data.can_manage && pretrip?`<form class="funding-toolbar" method="post" action="${window.TC_BASE_URL}/actions/dispatch.php">${Object.entries({csrf:data.assignment_csrf,reservation_id:data.trip.reservation_id,vehicle_id:data.trip.vehicle_id,driver_id:data.trip.driver_id,departure:data.trip.departure,notes:data.trip.notes,dispatch_action:'dispatch',return:location.pathname+location.search}).map(([key,value])=>`<input type="hidden" name="${key}" value="${esc(value)}">`).join('')}<button class="tc-btn tc-btn-primary" type="submit" ${data.readiness.ready?'':'disabled'}><i class="bi bi-send-check" aria-hidden="true"></i> Dispatch Trip</button></form>`:''}`;
  if(confirmed && pretrip && data.can_manage){const revise=document.createElement('button');revise.type='button';revise.className='tc-btn tc-btn-secondary tc-btn-sm mt-2';revise.textContent='Revise Funding';revise.addEventListener('click',async()=>{revise.disabled=true;try{const fields=new URLSearchParams({csrf:data.csrf,trip_id:data.trip.id,action:'revise'});const response=await fetch(`${window.TC_BASE_URL}/actions/trip-funding.php`,{method:'POST',body:fields,credentials:'same-origin'});const result=await response.json();if(!result.ok)throw Error(result.error);render(result.data);}catch(error){body.querySelector('#funding-error').textContent=error.message;revise.disabled=false;}});body.append(revise);}
  body.querySelector('#funding-request-form')?.addEventListener('submit',send);
  clearTimeout(timer);if(pending)timer=setTimeout(refresh,500);
 }
 async function refresh(){if(!current)return;const token=serial;try{const data=await load(new URLSearchParams({trip_id:current.trip.id}));if(token===serial){if(sending && data.status==='Not Requested'){timer=setTimeout(refresh,200);return;}render(data);}}catch(error){const errorBox=body.querySelector('#funding-error');if(errorBox)errorBox.textContent=error.message;}}
 async function send(event){
  event.preventDefault();if(sending)return;sending=true;const form=event.currentTarget,token=serial;const fields=new FormData(form);fields.set('trip_id',current.trip.id);fields.set('csrf',current.csrf);
  form.querySelectorAll('button,input,select').forEach(el=>el.disabled=true);form.querySelector('button').textContent='Sending Request to Finance…';
  body.querySelector('.funding-status').innerHTML='<span class="spinner-border spinner-border-sm" aria-hidden="true"></span> Sending Request to Finance…';
  timer=setTimeout(refresh,200);
  try{const response=await fetch(`${window.TC_BASE_URL}/actions/trip-funding.php`,{method:'POST',body:fields,credentials:'same-origin'});const result=await response.json();if(token!==serial)return;if(!result.ok)throw Error(result.error);sending=false;render(result.data);}catch(error){if(token!==serial)return;sending=false;clearTimeout(timer);await refresh();body.querySelector('#funding-error').textContent=error.message;}
 }
 window.TripFunding={async open(reservationId,tripId){serial++;clearTimeout(timer);const token=serial;current=null;body.textContent='Loading Trip Funding…';bootstrap.Modal.getOrCreateInstance(modal).show();try{const data=await load(new URLSearchParams(tripId?{trip_id:tripId}:{reservation_id:reservationId}));if(token===serial)render(data);}catch(error){if(token===serial)body.textContent=error.message;}}};
 modal.addEventListener('hidden.bs.modal',()=>{serial++;clearTimeout(timer);current=null;sending=false;});
})();
