<?php
if(PHP_SAPI!=='cli') { http_response_code(404); exit; }
$_SERVER['SCRIPT_NAME']='/fleet/archive.php';
require_once dirname(__DIR__).'/includes/bootstrap.php';
require_once ROOT_PATH.'/includes/archive.php';
$_SESSION['last_valid_activity']=time();
$db=db(); $passed=0;
function check_archive(bool $ok,string $label): void { global $passed; if(!$ok) throw new RuntimeException($label); $passed++; }
function archive_test_role(string $role,array $permissions=['archive.view','archive.trips','archive.retire','dispatch.view','dispatch.manage','vehicles.view']): void {
    global $current_user,$current_permissions;
    $current_user=['id'=>1,'role_code'=>$role,'role_name'=>'Test role','name'=>'Archive Test Operator','emp_id'=>'TEST','email'=>'test@example.invalid','avatar'=>null];
    $current_permissions=$permissions;
}
function archive_test_reject(callable $fn,string $label): void {
    try { $fn(); } catch(DomainException $e) { check_archive(true,$label); return; }
    throw new RuntimeException($label);
}
// Connection-local temporary tables shadow production data; service transactions cannot affect real records.
foreach(['trips','vehicles','reservations','drivers','users','maintenance_orders','fuel_transactions','trip_timeline','audit_logs'] as $table) {
    $db->exec("CREATE TEMP TABLE $table (LIKE public.$table INCLUDING DEFAULTS INCLUDING CONSTRAINTS)");
}
foreach(['trip_timeline','audit_logs'] as $table) {
    $db->exec("ALTER TABLE $table ALTER COLUMN id DROP DEFAULT");
    $db->exec("ALTER TABLE $table ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY");
}
$db->exec("CREATE TRIGGER archive_vehicle_lifecycle BEFORE UPDATE ON vehicles FOR EACH ROW EXECUTE FUNCTION public.archive_vehicle_lifecycle_guard()");
$db->exec("CREATE TRIGGER archive_trip_lifecycle BEFORE INSERT OR UPDATE ON trips FOR EACH ROW EXECUTE FUNCTION public.archive_trip_lifecycle_guard()");
$db->exec("INSERT INTO users(id,emp_id,name,email,password_hash,role_id) VALUES (1,'TEST','Archive Test Operator','test@example.invalid','unused',1)");
$db->exec("INSERT INTO drivers(id,name) VALUES ('TEST-DRIVER','Danilo Test')");
$db->exec("INSERT INTO vehicles(id,plate_number,type,brand,model,year,capacity,status) VALUES ('TEST-VEH','TEST123','Van','Toyota','Hiace',2020,12,'Available'),('TEST-ACTIVE','TEST456','Van','Toyota','Hiace',2021,12,'Available')");
$insert=$db->prepare("INSERT INTO trips(id,origin,destination,vehicle_id,driver_id,status,scheduled_departure,completion_notes) VALUES (?,'Terminal A','Terminal B','TEST-VEH','TEST-DRIVER',?,'2026-09-15 08:00','Historical reason retained')");
foreach(['Completed','Cancelled','Incomplete','In Transit','Scheduled','Assigned','Dispatched','Returning to Depot'] as $i=>$status) $insert->execute(['TEST-TRIP-'.$i,$status]);
$db->exec("INSERT INTO fuel_transactions(id,vehicle_id,driver_id,trip_id,transaction_date,liters,price_per_liter,total_cost) VALUES ('TEST-FUEL','TEST-VEH','TEST-DRIVER','TEST-TRIP-0','2026-09-15',10,60,600)");
archive_test_role('driver'); check_archive(!archive_can_view()&&!archive_can_trips()&&!archive_can_retire(),'Driver denied');
archive_test_role('customer'); check_archive(!archive_can_view(),'Customer denied');
archive_test_role('staff',[]); check_archive(!archive_can_view(),'Unpermitted Staff denied');
archive_test_role('staff'); check_archive(archive_can_view()&&!archive_can_trips()&&!archive_can_retire()&&!isset(archive_categories()['vehicles']),'Staff is limited to permitted trip view');
archive_test_role('fleet_manager'); check_archive(archive_can_view()&&!archive_can_trips()&&!archive_can_retire()&&isset(archive_categories()['vehicles']),'Manager view only');
archive_test_reject(fn()=>archive_trip($db,'TEST-TRIP-0'),'Manager cannot archive');
archive_test_role('dispatcher'); check_archive(archive_can_trips()&&!archive_can_retire()&&!isset(archive_categories()['vehicles']),'Dispatcher trip management only');
archive_test_reject(fn()=>archive_retire_vehicle($db,'TEST-VEH','Sold/Disposed','',''),'Dispatcher cannot retire');
for($i=3;$i<8;$i++) archive_test_reject(fn()=>archive_trip($db,'TEST-TRIP-'.$i),'Active trip cannot archive');
for($i=0;$i<3;$i++) archive_trip($db,'TEST-TRIP-'.$i);
check_archive((int)$db->query('SELECT COUNT(*) FROM trips WHERE is_archived')->fetchColumn()===3,'Three closed categories archive manually');
check_archive((int)$db->query('SELECT COUNT(*) FROM audit_logs')->fetchColumn()===3,'Trip decisions audited');
check_archive($db->query("SELECT completion_notes FROM trips WHERE id='TEST-TRIP-2'")->fetchColumn()==='Historical reason retained','Notes retained');
check_archive($db->query("SELECT trip_id FROM fuel_transactions WHERE id='TEST-FUEL'")->fetchColumn()==='TEST-TRIP-0','Fuel relationship survives archiving');
archive_test_reject(fn()=>archive_trip($db,'TEST-TRIP-0'),'Duplicate archive rejected');
archive_test_role('fleet_admin');
archive_test_reject(fn()=>archive_retire_vehicle($db,'TEST-VEH','Sold/Disposed','',''),'Active assignment prevents retirement');
archive_test_reject(fn()=>archive_retire_vehicle($db,'TEST-ACTIVE','Other','',''),'Other explanation required');
archive_test_reject(fn()=>archive_retire_vehicle($db,'TEST-ACTIVE','','',''),'Retirement reason required');
check_archive(archive_recommendation($db,'TEST-ACTIVE')['reason']===null,'No fabricated recommendation');
$db->exec("INSERT INTO reservations(id,client_name,passenger_count,origin,destination,departure_date,assigned_vehicle_id,status) VALUES ('TEST-RES','Test Customer',4,'Terminal A','Terminal B','2026-10-10','TEST-ACTIVE','Assigned')");
archive_test_reject(fn()=>archive_retire_vehicle($db,'TEST-ACTIVE','Sold/Disposed','',''),'Future reservation prevents retirement');
$db->exec("UPDATE reservations SET status='Cancelled' WHERE id='TEST-RES'");
$order=$db->prepare("INSERT INTO maintenance_orders(id,vehicle_id,service_type,scheduled_date,status,estimated_cost) VALUES (?,'TEST-ACTIVE','Mechanical failure','2026-09-01','Completed',500)");
for($i=1;$i<=3;$i++) $order->execute(['TEST-WO-'.$i]);
check_archive(archive_recommendation($db,'TEST-ACTIVE')['reason']==='Repeated Mechanical Failure','Recommendation uses explicit real source records');
archive_retire_vehicle($db,'TEST-ACTIVE','Other','Sold after management review','Preserve records');
$v=$db->query("SELECT * FROM vehicles WHERE id='TEST-ACTIVE'")->fetch();
check_archive($v['status']==='Retired' && $v['is_archived'] && str_contains($v['retirement_notes'],'Sold after management review') && $v['retirement_recommendation']==='Repeated Mechanical Failure','Retirement metadata preserved');
try { $db->exec("UPDATE vehicles SET status='Available' WHERE id='TEST-ACTIVE'"); throw new RuntimeException('Retirement guard missing'); } catch(PDOException $e) { check_archive(true,'Older maintenance cannot reactivate retired vehicle'); }
try { $db->exec("UPDATE trips SET status='Dispatched' WHERE id='TEST-TRIP-0'"); throw new RuntimeException('Archive guard missing'); } catch(PDOException $e) { check_archive(true,'Archived status immutable'); }
for($i=10;$i<40;$i++) { $insert->execute(['TEST-TRIP-'.$i,'Completed']); archive_trip($db,'TEST-TRIP-'.$i); }
$r=archive_records($db,'completed',['q'=>'danilo','origin'=>'Terminal A','from'=>'2026-09-01','to'=>'2026-09-30','sort'=>'oldest','page'=>2]);
check_archive($r['total']===31 && count($r['rows'])===15 && $r['page']===2,'Case-insensitive search, filter, sort and backend pagination combine');
$r=archive_records($db,'completed',['q'=>"' OR 1=1 --"]); check_archive($r['total']===0,'Search SQL injection does not broaden results');
$r=archive_records($db,'vehicles',['reason'=>'Other','type'=>'Van']); check_archive($r['total']===1,'Contextual vehicle filters');
archive_test_reject(fn()=>archive_records($db,'completed',['from'=>'2026-02-30']),'Invalid calendar date rejected');
archive_test_reject(fn()=>archive_records($db,'completed',['from'=>'2026-09-30','to'=>'2026-09-01']),'Reversed date rejected');
check_archive((int)$db->query("SELECT COUNT(*) FROM maintenance_orders WHERE vehicle_id='TEST-ACTIVE'")->fetchColumn()===3,'Maintenance relationships survive retirement');
$db->exec("UPDATE trips SET status='Completed' WHERE NOT is_archived");
archive_retire_vehicle($db,'TEST-VEH','Sold/Disposed','','');
$historical=$db->query("SELECT t.id,d.name,v.id vehicle_id,v.status FROM trips t JOIN drivers d ON d.id=t.driver_id JOIN vehicles v ON v.id=t.vehicle_id WHERE t.id='TEST-TRIP-0'")->fetch();
check_archive($historical['id']==='TEST-TRIP-0' && $historical['name']==='Danilo Test' && $historical['vehicle_id']==='TEST-VEH' && $historical['status']==='Retired','Archived trip driver and vehicle remain correct after retirement');
if(in_array('--render', $argv,true)) {
    $_GET=['category'=>'completed']; ob_start(); require ROOT_PATH.'/archive.php'; $html=ob_get_clean();
    file_put_contents(ROOT_PATH.'/tmp/archive-test-populated.html',$html);
    unset($page_scripts);
    $_GET=['category'=>'incomplete','id'=>'TEST-TRIP-2']; ob_start(); require ROOT_PATH.'/archive-details.php'; $html=ob_get_clean();
    file_put_contents(ROOT_PATH.'/tmp/archive-test-details.html',$html);
}
echo "$passed Archive database and authorization checks passed. Only connection-local test fixtures used.\n";
