<?php
if(PHP_SAPI!=='cli') { http_response_code(404); exit; }
require dirname(__DIR__).'/includes/bootstrap.php';
require ROOT_PATH.'/includes/archive.php';
$current_user=db()->query("SELECT u.*,r.code role_code,r.name role_name FROM users u JOIN roles r ON r.id=u.role_id WHERE r.code='fleet_admin' AND u.status='Active' LIMIT 1")->fetch();
$pdo=db(); $passed=0;
function feedback_check(bool $ok,string $label): void { global $passed; if(!$ok) throw new RuntimeException($label); $passed++; }
foreach(['trips','vehicles','reservations','maintenance_orders','audit_logs','trip_timeline'] as $table) $pdo->exec("CREATE TEMP TABLE $table (LIKE public.$table INCLUDING DEFAULTS INCLUDING CONSTRAINTS)");
foreach(['audit_logs','trip_timeline'] as $table) { $pdo->exec("ALTER TABLE $table ALTER COLUMN id DROP DEFAULT"); $pdo->exec("ALTER TABLE $table ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY"); }
$pdo->exec("INSERT INTO vehicles(id,plate_number,type,brand,model,year,capacity,status) VALUES ('FB-VEH','FB123','Van','Toyota','Hiace',2020,12,'Available')");
$_SERVER['REQUEST_METHOD']='POST'; $_SESSION['archive_csrf']='feedback-test'; $_SESSION['last_valid_activity']=time();
foreach(['Completed','Cancelled','Incomplete'] as $status) {
    $id='FB-'.$status;
    $pdo->prepare("INSERT INTO trips(id,origin,destination,status) VALUES (?,'A','B',?)")->execute([$id,$status]);
    $_POST=['csrf'=>'feedback-test','confirmed'=>'1','action'=>'trip','id'=>$id];
    ob_start(); include ROOT_PATH.'/actions/archive.php'; $data=json_decode(ob_get_clean(),true);
    feedback_check($data['ok']===true && str_contains($data['message'],$id.' was archived successfully.'),'Success response '.$status);
    feedback_check($_SESSION['archive_success']===$data['message'],'Flash persists across reload '.$status);
    unset($_SESSION['archive_success']);
}
$_POST=['csrf'=>'feedback-test','confirmed'=>'1','action'=>'retire','id'=>'FB-VEH','reason'=>'Sold/Disposed'];
ob_start(); include ROOT_PATH.'/actions/archive.php'; $data=json_decode(ob_get_clean(),true);
feedback_check($data['ok']===true && str_contains($data['message'],'FB-VEH was retired successfully.'),'Retirement success response');
$is_driver=false; $is_customer=false; $active_page='feedback-test';
ob_start(); include ROOT_PATH.'/includes/footer.php'; $html=ob_get_clean();
feedback_check(str_contains($html,"App.showToast('Success'") && str_contains($html,'FB-VEH was retired successfully.'),'Footer displays success toast');
feedback_check(!isset($_SESSION['archive_success']),'Confirmation consumed once');
ob_start(); include ROOT_PATH.'/includes/footer.php'; $html=ob_get_clean();
feedback_check(!str_contains($html,"App.showToast('Success'"),'Refresh does not repeat old confirmation');
$_POST=['csrf'=>'feedback-test','confirmed'=>'1','action'=>'trip','id'=>'DOES-NOT-EXIST'];
ob_start(); include ROOT_PATH.'/actions/archive.php'; $data=json_decode(ob_get_clean(),true);
feedback_check(isset($data['error']) && !isset($_SESSION['archive_success']),'Failed decision has no success message');
echo "$passed Archive confirmation response, reload and one-time message checks passed. Only temporary database tables used.\n";
