CREATE TABLE IF NOT EXISTS operating_schedules (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    departure_time TIME NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'Active' CHECK (status IN ('Active', 'Inactive')),
    created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS operating_schedule_days (
    schedule_id INTEGER NOT NULL REFERENCES operating_schedules(id) ON DELETE CASCADE,
    iso_weekday SMALLINT NOT NULL CHECK (iso_weekday BETWEEN 1 AND 7),
    PRIMARY KEY (schedule_id, iso_weekday)
);

CREATE TABLE IF NOT EXISTS scheduled_departures (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_id INTEGER NOT NULL REFERENCES operating_schedules(id) ON DELETE RESTRICT,
    service_date DATE NOT NULL,
    schedule_name_snapshot VARCHAR(120) NOT NULL,
    departure_time_snapshot TIME NOT NULL,
    capacity INTEGER NOT NULL CHECK (capacity > 0),
    status VARCHAR(20) NOT NULL DEFAULT 'Open' CHECK (status IN ('Open', 'Closed', 'Dispatched', 'Completed', 'Cancelled')),
    assigned_vehicle_id VARCHAR(20) REFERENCES vehicles(id) ON DELETE RESTRICT,
    assigned_driver_id VARCHAR(20) REFERENCES drivers(id) ON DELETE RESTRICT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (schedule_id, service_date)
);

ALTER TABLE reservations
    ADD COLUMN IF NOT EXISTS departure_schedule_instance_id BIGINT REFERENCES scheduled_departures(id) ON DELETE RESTRICT;
ALTER TABLE reservations
    ADD COLUMN IF NOT EXISTS return_schedule_instance_id BIGINT REFERENCES scheduled_departures(id) ON DELETE RESTRICT;
ALTER TABLE reservations
    ADD COLUMN IF NOT EXISTS departure_schedule_name VARCHAR(120);
ALTER TABLE reservations
    ADD COLUMN IF NOT EXISTS return_schedule_name VARCHAR(120);

CREATE INDEX IF NOT EXISTS idx_operating_schedule_status_time ON operating_schedules(status, departure_time);
CREATE INDEX IF NOT EXISTS idx_scheduled_departures_date ON scheduled_departures(service_date, departure_time_snapshot);
CREATE INDEX IF NOT EXISTS idx_reservations_departure_schedule ON reservations(departure_schedule_instance_id);
CREATE INDEX IF NOT EXISTS idx_reservations_return_schedule ON reservations(return_schedule_instance_id);

COMMENT ON TABLE operating_schedules IS 'Reusable administrator-configured operating schedule templates.';
COMMENT ON TABLE scheduled_departures IS 'Dated schedule instances with immutable name/time snapshots and shared passenger capacity.';
