INSERT INTO roles (code, name, description) VALUES
('customer', 'Customer / User', 'Own reservations and trip history only')
ON CONFLICT (code) DO NOTHING;

ALTER TABLE users ADD COLUMN IF NOT EXISTS phone VARCHAR(40);
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS customer_id INTEGER REFERENCES users(id) ON DELETE RESTRICT;
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS return_time VARCHAR(20);
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS rejection_reason TEXT;
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS reviewed_by INTEGER REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS reviewed_at TIMESTAMP;
CREATE INDEX IF NOT EXISTS idx_res_customer ON reservations(customer_id);

CREATE TABLE IF NOT EXISTS reservation_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reservation_id VARCHAR(30) NOT NULL REFERENCES reservations(id) ON DELETE CASCADE,
  actor_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  status VARCHAR(30) NOT NULL,
  reason TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_res_events ON reservation_events(reservation_id, created_at);

CREATE TABLE IF NOT EXISTS driver_ratings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trip_id VARCHAR(20) NOT NULL UNIQUE REFERENCES trips(id) ON DELETE CASCADE,
  reservation_id VARCHAR(30) NOT NULL REFERENCES reservations(id) ON DELETE CASCADE,
  customer_id INTEGER NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  driver_id VARCHAR(20) NOT NULL REFERENCES drivers(id) ON DELETE RESTRICT,
  stars SMALLINT NOT NULL CHECK (stars BETWEEN 1 AND 5),
  feedback TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_driver_ratings_driver ON driver_ratings(driver_id);
