<?php
/** Current business definitions, queried inside a single repeatable-read snapshot. */
function reports_metric(string $label,$value,string $type='integer'): array { return ['label'=>$label,'value'=>$value===null?null:(is_numeric($value)?(float)$value:$value),'type'=>$type]; }
function reports_query_row(PDO $pdo,string $sql,array $params=[]): array { $q=$pdo->prepare($sql); $q->execute($params); return $q->fetch()?:[]; }
function reports_definition(PDO $pdo,string $type,array $range): array
{
    $p=[$range['start'],$range['end']]; $c=reports_trip_cte();
    $col=fn($label,$kind='text',$width=22)=>reports_column($label,$kind,$width);
    $historical='Archived trips and retired vehicle relationships are retained. Archiving dates do not change the reporting period.';
    $tripRule='Trip period: cancellation time when recorded for cancelled trips; otherwise arrival, then departure, schedule, or creation time. Distances are stored trip distances, not verified fuel-consumption measurements.';
    if($type==='trips') {
        $a=reports_query_row($pdo,"WITH $c SELECT COUNT(*) total,COUNT(*) FILTER(WHERE status='Completed') completed,COUNT(*) FILTER(WHERE status='Cancelled') cancelled,COUNT(*) FILTER(WHERE status='Incomplete') incomplete,COUNT(*) FILTER(WHERE is_archived) archived,COALESCE(SUM(distance_km) FILTER(WHERE status='Completed'),0) distance FROM cohort",$p);
        $columns=['trip_id'=>$col('Trip ID','id',20),'reservation_id'=>$col('Reservation ID','id',24),'driver_id'=>$col('Driver ID','id',20),'driver'=>$col('Driver', 'text',26),'vehicle_id'=>$col('Vehicle ID','id',20),'plate'=>$col('Plate Number', 'id',18),'status'=>$col('Trip Status'),
            'passengers'=>$col('Passengers','integer',16),'origin'=>$col('Terminal A / Origin','text',34),'destination'=>$col('Terminal B / Destination','text',34),'route'=>$col('Route / Waypoints','text',40),'scheduled'=>$col('Scheduled Departure','datetime',26),'departure'=>$col('Actual Departure','datetime',26),'arrival'=>$col('Actual Arrival','datetime',26),'distance'=>$col('Recorded Distance (km)','decimal',24),'notes'=>$col('Completion / Interruption Notes','text',45),'archived'=>$col('Archived', 'text',14),'archived_date'=>$col('Archived Date','datetime',26)];
        return ['metrics'=>[reports_metric('Total trips',$a['total']),reports_metric('Completed',$a['completed']),reports_metric('Cancelled',$a['cancelled']),reports_metric('Incomplete',$a['incomplete']),reports_metric('Other statuses',$a['total']-$a['completed']-$a['cancelled']-$a['incomplete']),reports_metric('Archived trips included',$a['archived']),reports_metric('Completed distance (km)',$a['distance'],'decimal')],
            'notes'=>[$historical,$tripRule],'sections'=>['records'=>['title'=>'Trip Operations','columns'=>$columns,'params'=>$p,
                'sql'=>"WITH $c SELECT t.id trip_id,t.reservation_id,t.driver_id,d.name driver,t.vehicle_id,v.plate_number plate,t.status,t.passengers,t.origin,t.destination,t.waypoints route,t.scheduled_departure scheduled,t.actual_departure departure,t.actual_arrival arrival,t.distance_km distance,t.completion_notes notes,CASE WHEN t.is_archived THEN 'Yes' ELSE 'No' END archived,t.archived_at archived_date FROM cohort t LEFT JOIN drivers d ON d.id=t.driver_id LEFT JOIN vehicles v ON v.id=t.vehicle_id ORDER BY t.scheduled_departure NULLS LAST,t.id",
                'pdf_groups'=>[['trip_id','reservation_id','driver','vehicle_id','plate','status','passengers'],['trip_id','origin','destination','route','scheduled','departure','arrival','distance'],['trip_id','driver_id','notes','archived','archived_date']]]]];
    }
    if($type==='reservations') {
        $a=reports_query_row($pdo,"SELECT COUNT(*) total,COALESCE(SUM(passenger_count),0) passengers,COUNT(*) FILTER(WHERE status='Cancelled') cancelled,COUNT(*) FILTER(WHERE status='Rejected') rejected,COUNT(*) FILTER(WHERE status='Approved') approved FROM reservations WHERE departure_date>=?::date AND departure_date<?::date",$p);
        $columns=['reservation_id'=>$col('Reservation ID','id',24),'trip_id'=>$col('Trip ID','id',20),'customer'=>$col('Customer / Booking','text',30),'passengers'=>$col('Passenger Count','integer',18),'origin'=>$col('Terminal A / Origin','text',34),'destination'=>$col('Terminal B / Destination','text',34),'schedule'=>$col('Departure Schedule','text',30),'date'=>$col('Departure Date','date',20),'time'=>$col('Departure Time','text',18),
            'vehicle_id'=>$col('Assigned / Previous Vehicle ID','id',28),'plate'=>$col('Plate Number','id',18),'driver'=>$col('Assigned / Previous Driver','text',28),'status'=>$col('Reservation Status', 'text',24),'dispatch'=>$col('Latest Trip / Dispatch Status','text',28),'created'=>$col('Booked On','datetime',26),'reviewed'=>$col('Reviewed On','datetime',26),'cancelled'=>$col('Cancelled On','datetime',26),'reason'=>$col('Cancellation / Rejection Reason','text',40)];
        return ['metrics'=>[reports_metric('Reservations',$a['total']),reports_metric('Booked passengers',$a['passengers']),reports_metric('Approved',$a['approved']),reports_metric('Rejected',$a['rejected']),reports_metric('Cancelled',$a['cancelled'])],
            'notes'=>['Reservation period follows the scheduled departure date. One row per booking; the latest linked trip is shown when multiple trips exist. Cancellation retains previous vehicle and driver assignments.','A separate dispatch timestamp is not stored consistently; no inferred dispatch time is reported.',$historical],
            'sections'=>['records'=>['title'=>'Reservation & Dispatch Records','columns'=>$columns,'params'=>$p,
                'sql'=>"SELECT r.id reservation_id,t.id trip_id,r.client_name customer,r.passenger_count passengers,r.origin,r.destination,r.departure_schedule_name schedule,r.departure_date date,r.departure_time time,COALESCE(r.assigned_vehicle_id,r.cancelled_vehicle_id) vehicle_id,v.plate_number plate,d.name driver,r.status,t.status dispatch,r.created_at created,r.reviewed_at reviewed,r.cancelled_at cancelled,COALESCE(r.cancellation_reason,r.rejection_reason) reason FROM reservations r LEFT JOIN LATERAL(SELECT id,status FROM trips WHERE reservation_id=r.id ORDER BY created_at DESC,id DESC LIMIT 1) t ON TRUE LEFT JOIN vehicles v ON v.id=COALESCE(r.assigned_vehicle_id,r.cancelled_vehicle_id) LEFT JOIN drivers d ON d.id=COALESCE(r.assigned_driver_id,r.cancelled_driver_id) WHERE r.departure_date>=?::date AND r.departure_date<?::date ORDER BY r.departure_date,r.id",
                'pdf_groups'=>[['reservation_id','trip_id','customer','passengers','vehicle_id','plate','driver','status'],['reservation_id','origin','destination','schedule','date','time','dispatch'],['reservation_id','created','reviewed','cancelled','reason']]]]];
    }
    if($type==='drivers') {
        $sql="WITH $c, perf AS(SELECT driver_id,COUNT(*) assigned,COUNT(*) FILTER(WHERE status='Completed') completed,COUNT(*) FILTER(WHERE status='Cancelled') cancelled,COUNT(*) FILTER(WHERE status='Incomplete') incomplete,COUNT(*) FILTER(WHERE status IN ('Completed','Cancelled','Incomplete')) closed,
            COUNT(*) FILTER(WHERE status='Completed' AND actual_departure IS NOT NULL AND scheduled_departure IS NOT NULL) measurable,
            COUNT(*) FILTER(WHERE status='Completed' AND actual_departure IS NOT NULL AND scheduled_departure IS NOT NULL AND actual_departure<=scheduled_departure+INTERVAL '15 minutes') on_time,
            COALESCE(SUM(distance_km) FILTER(WHERE status='Completed'),0) distance FROM cohort GROUP BY driver_id), ratings AS(SELECT dr.driver_id,COUNT(*) rating_count,AVG(dr.stars) average FROM driver_ratings dr JOIN cohort t ON t.id=dr.trip_id GROUP BY dr.driver_id)
            SELECT d.id driver_id,d.name driver,COALESCE(p.assigned,0) assigned,COALESCE(p.completed,0) completed,COALESCE(p.cancelled,0) cancelled,COALESCE(p.incomplete,0) incomplete,CASE WHEN p.closed>0 THEN p.completed::numeric/p.closed END completion_rate,COALESCE(p.measurable,0) measurable,CASE WHEN p.measurable>0 THEN p.on_time::numeric/p.measurable END punctuality,COALESCE(p.distance,0) distance,COALESCE(r.rating_count,0) rating_count,r.average rating FROM drivers d LEFT JOIN perf p ON p.driver_id=d.id LEFT JOIN ratings r ON r.driver_id=d.id WHERE p.assigned>0 ORDER BY d.id";
        $a=reports_query_row($pdo,"WITH rows AS ($sql) SELECT COUNT(*) drivers,COALESCE(SUM(assigned),0) assigned,COALESCE(SUM(completed),0) completed,COALESCE(SUM(cancelled),0) cancelled,COALESCE(SUM(incomplete),0) incomplete,COALESCE(SUM(measurable),0) measurable FROM rows",$p);
        $columns=['driver_id'=>$col('Driver ID','id',20),'driver'=>$col('Driver Name','text',28),'assigned'=>$col('Assigned Trips','integer',18),'completed'=>$col('Completed Trips','integer',18),'cancelled'=>$col('Cancelled Trips','integer',18),'incomplete'=>$col('Incomplete Trips','integer',18),'completion_rate'=>$col('Closed-Trip Completion Rate','percent',30),'measurable'=>$col('Punctuality Sample','integer',22),'punctuality'=>$col('On-Time Departure Rate','percent',26),'distance'=>$col('Completed Distance (km)','decimal',26),'rating_count'=>$col('Customer Reviews','integer',22),'rating'=>$col('Average Customer Rating / 5','decimal',30)];
        return ['metrics'=>[reports_metric('Drivers with trips',$a['drivers']),reports_metric('Assigned trips',$a['assigned']),reports_metric('Completed',$a['completed']),reports_metric('Cancelled',$a['cancelled']),reports_metric('Incomplete',$a['incomplete']),reports_metric('Measured departures',$a['measurable'])],
            'notes'=>[$tripRule,'Completion rate = Completed ÷ (Completed + Cancelled + Incomplete). Ongoing trips are excluded from this denominator. On-time rate = completed trips departing no more than 15 minutes after schedule ÷ completed trips with both departure timestamps. Missing samples remain unavailable.','Ratings average actual customer reviews linked to the period’s trips. No synthetic safety, HRMS, incident or fuel-efficiency scores are used.',$historical],
            'sections'=>['records'=>['title'=>'Driver Performance','columns'=>$columns,'sql'=>$sql,'params'=>$p,
                'pdf_groups'=>[['driver_id','driver','assigned','completed','cancelled','incomplete','completion_rate'],['driver_id','measurable','punctuality','distance','rating_count','rating']]]]];
    }
    if($type==='fuel') {
        $source=cost_sources_sql(true);
        $ledger="WITH costs AS($source) SELECT c.source_id,c.trip_id,c.vehicle_id,v.plate_number plate,c.category,c.occurred_at date,c.amount,f.id fuel_id,f.driver_id,d.name driver,f.liters,f.price_per_liter price,f.station,f.receipt_no receipt FROM costs c LEFT JOIN vehicles v ON v.id=c.vehicle_id LEFT JOIN fuel_transactions f ON c.category='Fuel' AND f.id=c.source_id LEFT JOIN drivers d ON d.id=f.driver_id WHERE c.occurred_at>=?::date AND c.occurred_at<?::date";
        $cost=cost_summary($pdo,$range['start'],$range['end']);
        $a=reports_query_row($pdo,'SELECT COUNT(*) records,COALESCE(SUM(liters),0) liters,COALESCE(SUM(total_cost),0) fuel FROM fuel_transactions WHERE transaction_date>=?::date AND transaction_date<?::date',$p);
        $categories=reports_query_row($pdo,"WITH costs AS($source) SELECT COALESCE(SUM(amount) FILTER(WHERE category='Maintenance'),0) maintenance,COALESCE(SUM(amount) FILTER(WHERE category='Toll'),0) toll FROM costs WHERE occurred_at>=?::date AND occurred_at<?::date",$p);
        $columns=['source_id'=>$col('Cost Source Record ID','id',24),'trip_id'=>$col('Trip ID','id',20),'vehicle_id'=>$col('Vehicle ID','id',20),'plate'=>$col('Plate Number','id',18),'category'=>$col('Cost Category','text',20),'date'=>$col('Cost Date','datetime',26),'amount'=>$col('Recorded Cost (PHP)','money',24),'fuel_id'=>$col('Fuel Record ID','id',24),'driver_id'=>$col('Driver ID','id',20),'driver'=>$col('Fuel Driver','text',26),'liters'=>$col('Fuel Quantity (L)','decimal',22),'price'=>$col('Fuel Price / L (PHP)','money',24),'station'=>$col('Fuel Station','text',30),'receipt'=>$col('Receipt Reference','id',24)];
        $vehicleSql="WITH ledger AS($ledger) SELECT vehicle_id,MAX(plate) plate,COUNT(*) records,COALESCE(SUM(amount) FILTER(WHERE category='Fuel'),0) fuel,COALESCE(SUM(amount) FILTER(WHERE category='Maintenance'),0) maintenance,COALESCE(SUM(amount) FILTER(WHERE category='Toll'),0) toll,SUM(amount) total FROM ledger GROUP BY vehicle_id ORDER BY vehicle_id NULLS LAST";
        $tripSql="WITH ledger AS($ledger) SELECT trip_id,COUNT(*) records,COALESCE(SUM(amount) FILTER(WHERE category='Fuel'),0) fuel,COALESCE(SUM(amount) FILTER(WHERE category='Maintenance'),0) maintenance,COALESCE(SUM(amount) FILTER(WHERE category='Toll'),0) toll,SUM(amount) total FROM ledger WHERE trip_id IS NOT NULL GROUP BY trip_id ORDER BY trip_id";
        $groupColumns=['records'=>$col('Cost Records','integer',18),'fuel'=>$col('Fuel Cost (PHP)','money',24),'maintenance'=>$col('Maintenance Estimate (PHP)','money',30),'toll'=>$col('Toll Cost (PHP)','money',24),'total'=>$col('Total Cost (PHP)','money',24)];
        return ['metrics'=>[reports_metric('Fuel records',$a['records']),reports_metric('Fuel purchased (L)',$a['liters'],'decimal'),reports_metric('Fuel cost',$a['fuel'],'money'),reports_metric('Maintenance estimates',$categories['maintenance'],'money'),reports_metric('Recorded tolls',$categories['toll'],'money'),reports_metric('TCAO operational cost',$cost['cost'],'money'),reports_metric('Confirmed booking revenue',$cost['revenue'],'money'),reports_metric('Revenue less recorded cost',$cost['margin'],'money')],
            'notes'=>['TCAO total = fuel transaction costs + stored estimates on completed maintenance orders + recorded tolls on completed trips. Maintenance estimates are not verified repair invoices. Stored driver allowances are excluded, matching current TCAO.','Dates follow fuel transaction date, maintenance scheduled/service date, and completed-trip arrival date. Revenue counts each completed reservation with a confirmed fare once, when a linked completed trip arrived within the period.','Fuel quantity represents purchases/refills. Reliable consumed-fuel measurements and comparable odometer intervals are unavailable, so fuel-consumption and efficiency ratios are not fabricated. Trip cost totals exclude unlinked costs; vehicle totals include them.',$historical],
            'sections'=>['records'=>['title'=>'Fuel & Cost Records','columns'=>$columns,'sql'=>$ledger.' ORDER BY c.occurred_at,c.category,c.source_id','params'=>$p,'totals'=>['amount'=>$cost['cost'],'liters'=>(float)$a['liters']],
                'pdf_groups'=>[['source_id','trip_id','vehicle_id','plate','category','date','amount'],['source_id','fuel_id','driver_id','driver','liters','price','station','receipt']]],
                'vehicles'=>['title'=>'Cost by Vehicle','columns'=>['vehicle_id'=>$col('Vehicle ID','id',20),'plate'=>$col('Plate Number','id',18)]+$groupColumns,'sql'=>$vehicleSql,'params'=>$p,'totals'=>['total'=>$cost['cost']]],
                'trips'=>['title'=>'Linked Trip Costs','columns'=>['trip_id'=>$col('Trip ID','id',20)]+$groupColumns,'sql'=>$tripSql,'params'=>$p]]];
    }
    if($type==='route') {
        $a=reports_query_row($pdo,"SELECT COUNT(*) plans,COUNT(*) FILTER(WHERE actual_duration_mins IS NOT NULL AND predicted_duration_mins>0) comparable FROM route_history WHERE generated_date>=?::date AND generated_date<?::date",$p);
        $columns=['plan_id'=>$col('Route / Plan ID','id',24),'trip_id'=>$col('Trip ID','id',20),'reservation_id'=>$col('Reservation ID','id',24),'driver'=>$col('Driver','text',26),'vehicle_id'=>$col('Vehicle ID','id',20),'plate'=>$col('Plate Number','id',18),'origin'=>$col('Origin','text',34),'destination'=>$col('Destination','text',34),'mode'=>$col('Recorded Route Mode','text',32),'selected'=>$col('Selected Alternative','text',36),'distance'=>$col('Selected Distance (km)','decimal',26),'estimated'=>$col('Estimated Duration (min)','decimal',28),'actual'=>$col('Recorded Actual Duration (min)','decimal',30),'deviation'=>$col('Absolute Duration Deviation','percent',30),'generated'=>$col('Plan Generated','datetime',26)];
        return ['metrics'=>[reports_metric('Saved plans',$a['plans']),reports_metric('Plans with measured duration',$a['comparable'])],
            'notes'=>['Period follows the saved plan’s generation time. Route-mode labels are the actual saved TourSphere labels. Selected distance comes from the uniquely selected recorded alternative or saved route data.','A separate recommended alternative is not stored reliably and is not inferred. Absolute duration deviation = |actual − estimated| ÷ estimated, only when both recorded durations support it. No carbon-reduction or invented efficiency metric is included.',$historical],
            'sections'=>['records'=>['title'=>'Saved Route Plans','columns'=>$columns,'params'=>$p,
                'sql'=>"SELECT h.log_id plan_id,h.trip_id,h.reservation_id,d.name driver,COALESCE(h.vehicle_id,t.vehicle_id) vehicle_id,v.plate_number plate,h.origin,h.destination,h.selected_mode mode,s.summary_title selected,s.distance_km distance,h.predicted_duration_mins estimated,h.actual_duration_mins actual,CASE WHEN h.predicted_duration_mins>0 AND h.actual_duration_mins>=0 THEN ABS(h.actual_duration_mins-h.predicted_duration_mins)::numeric/h.predicted_duration_mins END deviation,h.generated_date generated,h.route_data_json _route FROM route_history h LEFT JOIN trips t ON t.id=h.trip_id LEFT JOIN drivers d ON d.id=t.driver_id LEFT JOIN vehicles v ON v.id=COALESCE(h.vehicle_id,t.vehicle_id) LEFT JOIN LATERAL(SELECT summary_title,distance_km FROM ai_route_candidates_log WHERE log_id=h.log_id AND is_selected=1 AND (SELECT COUNT(*) FROM ai_route_candidates_log WHERE log_id=h.log_id AND is_selected=1)=1 LIMIT 1) s ON TRUE WHERE h.generated_date>=?::date AND h.generated_date<?::date ORDER BY h.generated_date,h.log_id",
                'transform'=>static function(array $row): array { $data=json_decode((string)$row['_route'],true)?:[]; if($row['distance']===null && isset($data['distanceKm']) && is_numeric($data['distanceKm'])) $row['distance']=(float)$data['distanceKm']; return $row; },
                'pdf_groups'=>[['plan_id','trip_id','driver','vehicle_id','plate','mode'],['plan_id','origin','destination','selected','distance'],['plan_id','reservation_id','estimated','actual','deviation','generated']]]]];
    }
    if($type==='fleet') {
        $a=reports_query_row($pdo,"SELECT COUNT(*) total,COUNT(*) FILTER(WHERE status NOT IN ('Maintenance','Inactive','Retired')) active,COUNT(*) FILTER(WHERE status='Available') available,COUNT(*) FILTER(WHERE status='Maintenance') maintenance,COUNT(*) FILTER(WHERE status='Inactive') inactive,COUNT(*) FILTER(WHERE status='Retired') retired FROM vehicles");
        $columns=['vehicle_id'=>$col('Vehicle ID','id',20),'plate'=>$col('Plate Number','id',18),'type'=>$col('Vehicle Type','text',22),'brand'=>$col('Brand','text',22),'model'=>$col('Model','text',26),'status'=>$col('Current Fleet Status','text',24),'trips'=>$col('Period Trips','integer',18),'completed'=>$col('Completed Trips','integer',20),'distance'=>$col('Completed Distance (km)','decimal',26),'maintenance'=>$col('Period Maintenance Orders','integer',28),'registration'=>$col('Registration Review','text',26),'registration_expiry'=>$col('Registration Expiry','date',24),'insurance'=>$col('Insurance Review','text',26),'insurance_expiry'=>$col('Insurance Expiry','date',24),'permit'=>$col('LTFRB Permit Review','text',26),'permit_expiry'=>$col('LTFRB Permit Expiry','date',24),'eligible'=>$col('Current Operational Eligibility','text',34),'compliance_notes'=>$col('Eligibility / Missing Documents','text',52),'retired_at'=>$col('Retired On','datetime',26),'retirement_reason'=>$col('Retirement Reason','text',36)];
        $sql="WITH $c, utilization AS(SELECT vehicle_id,COUNT(*) trips,COUNT(*) FILTER(WHERE status='Completed') completed,COALESCE(SUM(distance_km) FILTER(WHERE status='Completed'),0) distance FROM cohort GROUP BY vehicle_id), repairs AS(SELECT vehicle_id,COUNT(*) maintenance FROM maintenance_orders WHERE scheduled_date>=?::date AND scheduled_date<?::date GROUP BY vehicle_id), docs AS(SELECT vehicle_id,CASE WHEN LOWER(document_type) IN ('or/cr','registration document') THEN 'registration' ELSE LOWER(document_type) END kind,extracted_data,extraction_status,ROW_NUMBER() OVER(PARTITION BY vehicle_id,CASE WHEN LOWER(document_type) IN ('or/cr','registration document') THEN 'registration' ELSE LOWER(document_type) END ORDER BY uploaded_at DESC,id DESC) rank FROM vehicle_documents), latest AS(SELECT vehicle_id,json_object_agg(kind,json_build_object('data',extracted_data,'status',extraction_status)) documents FROM docs WHERE rank=1 AND kind IN ('registration','insurance','ltfrb_permit') GROUP BY vehicle_id) SELECT v.id vehicle_id,v.plate_number plate,v.type,v.brand,v.model,v.status,COALESCE(u.trips,0) trips,COALESCE(u.completed,0) completed,COALESCE(u.distance,0) distance,COALESCE(rp.maintenance,0) maintenance,v.retired_at,v.retirement_reason,ld.documents _documents FROM vehicles v LEFT JOIN utilization u ON u.vehicle_id=v.id LEFT JOIN repairs rp ON rp.vehicle_id=v.id LEFT JOIN latest ld ON ld.vehicle_id=v.id ORDER BY v.id";
        return ['metrics'=>[reports_metric('Registered vehicles — current',$a['total']),reports_metric('Active fleet — current',$a['active']),reports_metric('Available — current',$a['available']),reports_metric('Maintenance — current',$a['maintenance']),reports_metric('Inactive — current',$a['inactive']),reports_metric('Retired — current',$a['retired'])],
            'notes'=>['Fleet status, registration, insurance, LTFRB review and operational eligibility are current snapshots at report generation. Historical availability and document validity cannot be reconstructed from the current database. Active fleet includes Available, Assigned and On Trip statuses; maintenance, inactive and retired vehicles are excluded.',$tripRule,'Utilization reports actual trip counts and recorded completed-trip distances; no availability percentage is invented. Maintenance frequency counts orders scheduled in the selected period.',$historical],
            'sections'=>['records'=>['title'=>'Fleet, Utilization & Compliance','columns'=>$columns,'sql'=>$sql,'params'=>array_merge($p,$p),
                'transform'=>static function(array $row): array {
                    $docs=json_decode((string)$row['_documents'],true)?:[];
                    foreach(['registration'=>'registration','insurance'=>'insurance','ltfrb_permit'=>'permit'] as $key=>$prefix) {
                        $doc=$docs[$key]??null; $row[$prefix]=$doc?(!empty($doc['data']['test_fixture'])?'TEST DATA · '.$doc['status']:$doc['status']):'Missing';
                        $date=$doc['data']['expiration_date']??null; $d=$date?DateTimeImmutable::createFromFormat('!Y-m-d',(string)$date):false;
                        $row[$prefix.'_expiry']=$d && $d->format('Y-m-d')===$date?$date:null;
                    }
                    $compliance=vehicle_compliance_evaluate($docs);
                    if(in_array($row['status'],['Retired','Inactive','Maintenance'],true)) { $row['eligible']='Not eligible — '.$row['status']; }
                    else $row['eligible']=$compliance['status'];
                    $row['compliance_notes']=$compliance['reason']; return $row;
                },
                'pdf_groups'=>[['vehicle_id','plate','type','brand','model','status'],['vehicle_id','trips','completed','distance','maintenance','retired_at','retirement_reason'],['vehicle_id','registration','registration_expiry','insurance','insurance_expiry','permit','permit_expiry'],['vehicle_id','eligible','compliance_notes']]]]];
    }
    throw new DomainException('Unknown report type.');
}
