<?php
/** Exporters only present the authorized snapshot; they never query business records. */
function reports_excel_text($value): string { return '<raw>'.htmlspecialchars((string)$value,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8').'</raw>'; }
function reports_excel_cell($value,array $column): mixed
{
    if($value===null || $value==='') return null;
    $type=$column['type'];
    if(in_array($type,['integer','decimal','money','percent'],true)) {
        $format=['integer'=>'#,##0','decimal'=>'#,##0.00','money'=>'"₱"#,##0.00;[Red]("₱"#,##0.00)','percent'=>'0.0%'][$type];
        return '<style nf="'.htmlspecialchars($format,ENT_QUOTES,'UTF-8').'">'.$value.'</style>';
    }
    if(in_array($type,['date','datetime'],true)) {
        $date=new DateTimeImmutable((string)$value);
        $wall=new DateTimeImmutable($date->format('Y-m-d H:i:s'),new DateTimeZone('UTC'));
        $serial=($wall->getTimestamp()-(new DateTimeImmutable('1899-12-30',new DateTimeZone('UTC')))->getTimestamp())/86400;
        return '<style nf="'.($type==='date'?'mmm d, yyyy':'mmm d, yyyy hh:mm').'">'.$serial.'</style>';
    }
    $text=reports_excel_text($value);
    $lines=max(1,ceil(mb_strlen((string)$value)/max(12,($column['width']??30)-2)),substr_count((string)$value,"\n")+1);
    return $type==='id'?'<b><style color="#24558A">'.$text.'</style></b>':'<style height="'.min(300,max(22,$lines*15)).'"><wraptext>'.$text.'</wraptext></style>';
}
function reports_excel_letter(int $i): string { $s=''; while($i>0) { $i--; $s=chr(65+$i%26).$s; $i=intdiv($i,26); } return $s; }
function reports_export_xlsx(array $m,string $path): void
{
    require_once ROOT_PATH.'/lib/reporting/SimpleXLSXGen.php';
    $xlsx=new \Shuchkin\SimpleXLSXGen(); $xlsx->setDefaultFont('Calibri')->setDefaultFontSize(11);
    $text='reports_excel_text';
    $summary=[['<b><style font-size="18" color="#24558A">'.$text($m['company']).'</style></b>'],['Fleet & Transportation Management'],['<b>'.$text($m['title']).'</b>'],[$text('Reporting Period: '.$m['range']['label'])],[$text('Generated: '.$m['generated_at'].' · '.$m['timezone'])],[$text('Generated By: '.$m['generated_by'].' · '.$m['generated_role'])],[],['<b>Operational Summary</b>']];
    $summary[7]=['<style bgcolor="#EAF1FA" height="28"><b>Operational Summary</b></style>','<style bgcolor="#EAF1FA"><b>Value</b></style>'];
    foreach($m['metrics'] as $metric) $summary[]=['<style height="25">'.$text($metric['label']).'</style>',reports_excel_cell($metric['value'],['type'=>$metric['type']])];
    $summary[]=[]; $summary[]=['<b>Reporting Notes & Definitions</b>'];
    foreach($m['notes'] as $note) $summary[]=['<style height="60"><wraptext>'.$text($note).'</wraptext></style>'];
    $summary[]=['Snapshot available for 30 minutes. Refresh Preview to include subsequent changes.'];
    $xlsx->addSheet($summary,'Summary')->setColWidth(1,90)->setColWidth(2,26)->freezePanes('A9');
    foreach($m['sections'] as $key=>$s) {
        $cols=$s['columns']; $last=reports_excel_letter(count($cols));
        $rows=[['<b>'.$text($m['company']).'</b>'],[$text($m['title'].' · '.$s['title'])],[$text('Reporting Period: '.$m['range']['label'])],[$text('Generated: '.$m['generated_at'].' · '.$m['generated_by'])],[],array_values(array_map(static fn($c)=>'<style bgcolor="#EAF1FA" height="42"><b><wraptext>'.htmlspecialchars($c['label'],ENT_QUOTES,'UTF-8').'</wraptext></b></style>',$cols))];
        foreach(reports_rows($m,$key) as $row) { $cells=[]; foreach($cols as $field=>$column) $cells[]=reports_excel_cell($row[$field]??null,$column); $rows[]=$cells; }
        $dataEnd=count($rows);
        if(!$s['count']) $rows[]=['No report data is available for the selected period.'];
        if($s['totals']) { $totals=[]; foreach($cols as $field=>$column) $totals[]=isset($s['totals'][$field])?reports_excel_cell($s['totals'][$field],$column):null; $totals[0]='<b>Grand Total</b>'; $rows[]=$totals; }
        $name=substr(str_replace(['[',']',':','*','?','/','\\'],'',$s['title']),0,31);
        $xlsx->addSheet($rows,$name)->freezePanes('A7');
        if($s['count']) $xlsx->autoFilter('A6:'.$last.$dataEnd);
        for($i=1;$i<=4;$i++) $xlsx->mergeCells('A'.$i.':'.$last.$i);
        $i=1; foreach($cols as $column) $xlsx->setColWidth($i++,$column['width']);
    }
    if(!$xlsx->saveAs($path)) throw new RuntimeException('Workbook generation failed.');
}
function reports_export_csv(array $m,string $path): void
{
    $f=fopen($path,'wb'); if(!$f) throw new RuntimeException('CSV storage unavailable.');
    try {
        fwrite($f,"\xEF\xBB\xBF"); $cols=$m['sections']['records']['columns']; fputcsv($f,array_column($cols,'label'),',','"','');
        foreach(reports_rows($m,'records') as $row) {
            $values=[];
            foreach($cols as $field=>$column) { $v=$row[$field]??''; if($v!==null && !in_array($column['type'],['integer','decimal','money','percent'],true) && preg_match('/^[\s]*[=+@-]/u',(string)$v)) $v="'".$v; $values[]=$v; }
            if(fputcsv($f,$values,',','"','')===false) throw new RuntimeException('CSV generation failed.');
        }
    } finally { fclose($f); }
}
function reports_export_pdf(array $m,string $path): void
{
    require_once ROOT_PATH.'/lib/reporting/dompdf/autoload.inc.php';
    $esc=static fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');
    $html='<html><head><meta charset="utf-8"><style>@page{margin:48px 30px 44px}body{font-family:DejaVu Sans;font-size:9px;color:#1f2937}h1{font-size:22px;color:#24558a;margin:8px 0}h2{font-size:15px;margin:18px 0 8px}p{line-height:1.5;margin:5px 0}.brand{font-size:18px;font-weight:bold;color:#24558a}.muted{color:#6b7280}.metrics{width:100%;border-collapse:collapse}.metrics td{padding:9px;background:#f8fafc;border:1px solid #eef2f7}.metrics strong{font-size:15px}.records{width:100%;border-collapse:collapse;table-layout:fixed}.records th{background:#eaf1fa;text-align:left;font-size:8px}.records td,.records th{padding:6px 5px;border-bottom:1px solid #e3e8ef;overflow-wrap:break-word;word-wrap:break-word;vertical-align:top}.records td{font-size:8px}thead{display:table-header-group}tr{page-break-inside:avoid}td.identifier{font-weight:bold;color:#24558a}td.number{text-align:right}.block{page-break-before:always}.notes{font-size:8px;line-height:1.5}.total{background:#f0f4f8;font-weight:bold}.running{position:fixed;top:-30px;font-size:8px;color:#6b7280}</style></head><body><div class="running">'.$esc($m['company'].' · '.$m['title'].' · '.$m['range']['label']).'</div><div class="brand">'.$esc($m['company']).'</div><p class="muted">Fleet &amp; Transportation Management</p><h1>'.$esc($m['title']).'</h1><p>Reporting Period: <b>'.$esc($m['range']['label']).'</b></p><p class="muted">Generated: '.$esc($m['generated_at'].' · '.$m['timezone']).'<br>Generated By: '.$esc($m['generated_by'].' · '.$m['generated_role']).'</p><h2>Operational Summary</h2><table class="metrics">';
    foreach(array_chunk($m['metrics'],3) as $chunk) { $html.='<tr>'; foreach($chunk as $metric) $html.='<td>'.$esc($metric['label']).'<br><strong>'.$esc(reports_value($metric['value'],$metric['type'])).'</strong></td>'; $html.='</tr>'; }
    $html.='</table><h2>Reporting Notes &amp; Definitions</h2><div class="notes">'; foreach($m['notes'] as $note) $html.='<p>'.$esc($note).'</p>'; $html.='</div>';
    foreach($m['sections'] as $key=>$s) foreach($s['pdf_groups'] as $groupIndex=>$fields) {
        $html.='<div class="block"><h2>'.$esc($s['title']).'</h2><p class="muted">'.$s['count'].' records · '.($groupIndex+1).' of '.count($s['pdf_groups']).' detail sections · '.$esc($m['range']['label']).'</p><table class="records"><thead><tr>';
        foreach($fields as $field) $html.='<th>'.$esc($s['columns'][$field]['label']).'</th>'; $html.='</tr></thead><tbody>';
        foreach(reports_rows($m,$key) as $row) { $html.='<tr>'; foreach($fields as $field) { $col=$s['columns'][$field]; $class=$col['type']==='id'?'identifier':(in_array($col['type'],['integer','decimal','money','percent'],true)?'number':''); $html.='<td class="'.$class.'">'.$esc(reports_value($row[$field]??null,$col['type'])).'</td>'; } $html.='</tr>'; }
        if(!$s['count']) $html.='<tr><td colspan="'.count($fields).'">No report data is available for the selected period.</td></tr>';
        $html.='</tbody></table>';
        if($s['totals'] && $groupIndex===0) { $html.='<p class="total">Grand Total: '; foreach($s['totals'] as $field=>$value) $html.=$esc($s['columns'][$field]['label'].': '.reports_value($value,$s['columns'][$field]['type'])).' &nbsp; '; $html.='</p>'; }
        $html.='</div>';
    }
    $html.='</body></html>';
    $options=new \Dompdf\Options(); $options->set('isRemoteEnabled',false); $options->set('isPhpEnabled',false); $options->set('isJavascriptEnabled',false); $options->set('defaultFont','DejaVu Sans'); $options->set('tempDir',reports_storage());
    $pdf=new \Dompdf\Dompdf($options); $pdf->setPaper('A4','landscape'); $pdf->loadHtml($html,'UTF-8'); $pdf->render();
    $canvas=$pdf->getCanvas(); $font=$pdf->getFontMetrics()->getFont('DejaVu Sans','normal');
    $canvas->page_text(32,566,'TourSphere · '.$m['generated_at'],$font,7,[0.4,0.45,0.5]); $canvas->page_text(720,566,'Page {PAGE_NUM} of {PAGE_COUNT}',$font,7,[0.4,0.45,0.5]);
    if(file_put_contents($path,$pdf->output())===false) throw new RuntimeException('PDF generation failed.');
}
