<?php
require_once ROOT_PATH.'/includes/trip_funding.php';
$fuelDriverId=null;
if(has_role('driver')){$d=$pdo->prepare('SELECT id FROM drivers WHERE user_id=?');$d->execute([current_user()['id']]);$fuelDriverId=$d->fetchColumn() ?: '__none__';}
$fuelComparisons=funding_comparison_rows($pdo,date('Y-01-01'),date('Y-m-d',strtotime('+1 year')),$fuelDriverId,null,20);
?>
<section class="tc-card mb-4"><div class="tc-card-header"><div><h2 class="fs-6 fw-bold mb-1">Trip Fuel: Estimated vs Actual</h2><p class="small text-muted-custom mb-0">20 recent trips. Actual consumption requires verified trip measurement. Refueling costs use the submitted pump price. No toll or parking costs included.</p></div></div><div class="tc-table-container"><table class="tc-table"><thead><tr><th>Trip</th><th>Estimated Consumption</th><th>Actual Consumption</th><th>Fuel Logged</th><th>Estimated Fuel Cost</th><th>Actual Fuel Cost</th><th>Reference Price / L</th><th>Actual Average Price / L</th><th>Variance</th></tr></thead><tbody>
<?php if(!$fuelComparisons): ?><tr><td colspan="9" class="text-center text-muted-custom">No trips available.</td></tr><?php endif; ?>
<?php foreach($fuelComparisons as $row):$variance=$row['actual_fuel_cost']!==null && $row['estimated_fuel_cost']!==null?(float)$row['actual_fuel_cost']-(float)$row['estimated_fuel_cost']:null; ?><tr><td><?= e($row['id']) ?></td><td><?= $row['estimated_liters']===null?'Not Available':number_format((float)$row['estimated_liters'],2).' L' ?></td><td><?= $row['verified_consumption']===null?'Not Recorded':number_format((float)$row['verified_consumption'],2).' L' ?></td><td><?= $row['actual_fuel_logged']===null?'Not Recorded':number_format((float)$row['actual_fuel_logged'],2).' L' ?></td><td><?= funding_money($row['estimated_fuel_cost'],'Not Available') ?></td><td><?= funding_money($row['actual_fuel_cost']) ?></td><td><?= funding_money($row['reference_price'],'Not Available') ?></td><td><?= funding_money($row['average_price']) ?></td><td><?= $variance===null?'Not Available':money(abs($variance)).($variance>0?' Over Estimate':($variance<0?' Under Estimate':' On Estimate')) ?></td></tr><?php endforeach; ?>
</tbody></table></div></section>
